### ISSUE TITLE
Edge case where it sometimes decides to use all available CPU 

### ISSUE THREAD

**Issue by alexkar598** [spacestation13/dm-playground_controller#12]
![image](https://user-images.githubusercontent.com/25136265/147506048-c9f15115-a257-4a22-b6e6-f88d5358d9bc.png)
![image](https://user-images.githubusercontent.com/25136265/147506051-ede37cbf-d138-4a41-90b5-9edba91706f6.png)

Haven't been able to get it to replicate after recompiling

**Comment by ZeWaka** [comment]
unable to reproduce

**Comment by optimumtact** [comment]
> unable to reproduce

fate of many developers im afraid, too much social skill required

**Comment by alexkar598** [comment]
Managed to replicate the issue with the tab closed. This is likely related to the memory leak and performance loss when opening devtools on firefox
