### ISSUE TITLE
command don't account for empty base64 strings

### ISSUE THREAD

**Issue by alexkar598** [spacestation13/dm-playground_controller#6]
`run L2Jpbi9zbGVlcA==  dGVzdD10cnVl` should work and parse down to, quotes excluded:
path: "/bin/sleep"
args: ""
env: "test=true"

However, it parsed as:
path: "/bin/sleep"
args: "test=true"
env: missing

And throws an invalid command error

**Comment by ZeWaka** [comment]
fixed the title but not the description
