### ISSUE TITLE
pidexit poll event returns a non base64 encoded string instead of an exit code

### ISSUE THREAD

**Issue by alexkar598** [spacestation13/dm-playground_controller#7]
```
OK
---
> run L2Jpbi9ob3N0bmFtZQ== LXM= dGVzdD10cnVl
---
< OK
< OK
---
> poll
---
< pidexit 58 Exited(0)
< OK
---
```

Should be `pidexit 58 0` not `pidexit 58 Exited(0)`

**Comment by ZeWaka** [comment]
I dunno, this provides a lot more information that you'd just be throwing away. See: if it exited with an exit code or if it was signaled with the signal number
